---
- name: (Fedora, CentOS, RedHat) install zookeeper
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  yum: state=present name=mesosphere-zookeeper

- name: (Ubuntu, Debian) install zookeeper
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  apt: state=present name=mesos

- name: (Fedora, CentOS, RedHat) set myid
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  template: >
    src=var/lib/zookeeper/myid.j2
    dest=/var/lib/zookeeper/myid
    owner=root
    group=root
    mode=0644

- name: (Ubuntu, Debian) set myid
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  template: >
    src=etc/zookeeper/conf/myid.j2
    dest=/etc/zookeeper/conf/myid
    owner=zookeeper
    group=zookeeper
    mode=0644

- name: install zoo.cfg
  template: >
    src=etc/zookeeper/conf/zoo.cfg.j2
    dest=/etc/zookeeper/conf/zoo.cfg
    owner=root
    group=root
    mode=0644

- name: launch zookeeper
  service: name=zookeeper enabled=yes state=started
