---
- name: install zookeeper
  yum: state=present name=mesosphere-zookeeper

- name: set myid
  template: >
    src=var/lib/zookeeper/myid.j2
    dest=/var/lib/zookeeper/myid
    owner=root
    group=root
    mode=0644

- name: install zoo.cfg
  template: >
    src=etc/zookeeper/conf/zoo.cfg.j2
    dest=/etc/zookeeper/conf/zoo.cfg
    owner=root
    group=root
    mode=0644

- name: launch zookeeper
  service: name=zookeeper enabled=yes state=started


    