---
- name: (Fedora, CentOS, RedHat) install mesos and marathon
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  yum: state=present name={{item}}
  with_items:
    - mesos
    - marathon

- name: (Ubuntu, Debian) install mesos and marathon
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  apt: state=present name={{item}}
  with_items:
    - mesos
    - marathon

- name: install /etc/mesos-master/* files
  template: >
    src=etc/mesos-master/{{item}}.j2
    dest=/etc/mesos-master/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - quorum
    - hostname
    - ip

- name: create /etc/marathon/conf
  file: >-
    owner=root
    group=root
    mode="go-w"
    path=/etc/marathon/conf
    state=directory
    
- name: install /etc/marathon/conf/* files
  template: >
    src=etc/marathon/conf/{{item}}.j2
    dest=/etc/marathon/conf/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - hostname
    
- name: start mesos-master service
  service: name={{item}} enabled=yes state=started
  with_items:
    - mesos-master
    - marathon
  