---
- name: (Fedora, CentOS, RedHat)install mesos and marathon
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  yum: state=present name={{item}}
  with_items:
    - mesos
    - marathon

- name: (Ubuntu, Debian) install mesos and marathon
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  apt: state=present name={{item}}
  with_items:
    - mesos
    - marathon

- name: install /etc/mesos-master/quorum
  template: >
    src=etc/mesos-master/quorum.j2
    dest=/etc/mesos-master/quorum
    owner=root
    group=root
    mode=0644

- name: start mesos-master service
  service: name={{item}} enabled=yes state=started
  with_items:
    - mesos-master
    - marathon
  