---
- name: (Fedora, CentOS, RedHat) install mesos
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  yum: state=present name={{item}}
  with_items:
    - mesos

- name: (Ubuntu, Debian) install mesos and marathon
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  apt: state=present name={{item}}
  with_items:
    - mesos

- name: install /etc/mesos-slave/* files
  template: >
    src=etc/mesos-slave/{{item}}.j2
    dest=/etc/mesos-slave/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - hostname
    - ip
  
- name: start mesos-slave service
  service: name={{item}} enabled=yes state=started
  with_items:
    - mesos-slave
