---
- name: launch bamboo
  docker:
    name: bamboo
    image: andrewrothstein/bamboo:blade
    pull: always
    env:
      MARATHON_ENDPOINT : "{% for host in groups['marathon'] %}http://{{hostvars[host]['ansible_default_ipv4']['address']}}:8080{% if not loop.last %},{% endif %}{% endfor %}"
      BAMBOO_ENDPOINT : 'http://bamboo:8000'
      BAMBOO_ZK_HOST : "{% for host in groups['zookeeper'] %}{{hostvars[host]['ansible_default_ipv4']['address']}}:2181{% if not loop.last %},{% endif %}{% endfor %}"
      BAMBOO_ZK_PATH : '/bamboo'
      BIND : ':8000'
      CONFIG_PATH : 'config/production.example.json'
      BAMBOO_DOCKER_AUTO_HOST : 'true'
    ports:
      - "80:80"
      - "8000:8000"
      
